version: '3.6'

# For local dev

services:

  displaytrigger:
    image: superlimitbreak/displaytrigger:latest
    build:
      context: ${ROOT_FOLDER}
      dockerfile: systemSetup/displaytrigger.dockerfile
    ports:
      - "80:80"
    volumes:
      - ${PATH_HOST_media}:/srv/media/:ro
      - ../displayTrigger/eventmap:/srv/eventmap/:ro
      #- ${PATH_HOST_media}/eventmap:/srv/eventmap/:ro  # Attempt to simplify the deployment. eventmap .json files are in the root of media
      #- ${PATH_HOST_media}/stageconfig:/srv/stageconfig/:ro
    links:
      - subscriptionserver

  subscriptionserver:
    image: superlimitbreak/subscriptionserver:latest
    build:
      context: ${ROOT_FOLDER}/multisocketServer/multisocketServer/server
    ports:
      - "9872:9872"
      - "9873:9873"
    #command: --tcp_port 9872 --websocket_port 9873 --log_level 10  # for debuging

  # subscriptionserver_bridge:
  #   image: superlimitbreak/subscriptionserver_bridge:latest
  #   build:
  #     context: ${ROOT_FOLDER}/multisocketServer/webBridge
  #   ports:
  #     - ${PORT_URL_WEBSOCKET_BRIDGE}:${PORT_URL_WEBSOCKET_BRIDGE}
  #   links:
  #     - subscriptionserver
  #   command: [
  #     '--port', '${PORT_URL_WEBSOCKET_BRIDGE}',
  #     '--subscription_server_hostname', 'multisocket_subscription_server:${PORT_TCP}',
  #   ]

  mediainfoservice:
    image: superlimitbreak/mediainfoservice:latest
    build:
      context: ${ROOT_FOLDER}/mediaInfoService
    volumes:
      - ${PATH_HOST_media}:/srv/media:ro
    ports:
      - "8331:8331"
    command: /srv/media

  stageorchestration:
    image: superlimitbreak/stageorchestration:latest
    build:
      context: ${ROOT_FOLDER}/stageOrchestration
    ports:
      - "23487:23487"
    #volumes:
      #- ${PATH_HOST_media}/stageOrchestrationSequences:/stageOrchestration/data/sequences/:ro
      #- ${PATH_HOST_media}/stageDescription:/stageOrchestration/data/stageDescription/:ro
    links:
      - mediainfoservice
      - subscriptionserver
    command: --config=config.development.yaml --displaytrigger_host=subscriptionserver --mediainfo_host=mediainfoservice:8331

  # TODO: Add falcon_bridge
  # TODO: Add udp->websocket bridge?
  # TODO: Add mediaTimelineRenderer
