version: '3.6'

services:

  displaytrigger:
    image: superlimitbreak/displaytrigger:latest
    ports:
      - "80:80"
    volumes:
      - ${PATH_HOST_media}:/srv/media/:ro
      #- ${ROOT_FOLDER}/displayTrigger/eventmap:/srv/eventmap/:ro
      #- ${PATH_HOST_media}/eventmap:/srv/eventmap/:ro  # Attempt to simplify the deployment. eventmap .json files are in the root of media
      #- ${PATH_HOST_media}/stageconfig:/srv/stageconfig/:ro
    links:
      - subscriptionserver  # temp
      #- subscriptionserver_bridge
      - mediainfoservice
      #- stageorchestration

  subscriptionserver:
    image: superlimitbreak/subscriptionserver2:latest
    ports:
      - "9873:9873"
    #command: --log_level 10  # for debuging

  # subscriptionserver_bridge:  # temp
  #   image: superlimitbreak/subscriptionserver_bridge:latest
  #   expose:
  #     - 10794
  #   links:
  #      - subscriptionserver
  #   command: [
  #     'subscriptionserver:9872',
  #     '--port', '10794',
  #   ]

  mediainfoservice:
    image: superlimitbreak/mediainfoservice:latest
    volumes:
      - ${PATH_HOST_media}:/srv/media:ro
    expose:
      - 8331
    command: [
      '/srv/media',
    ]

  mediatimelinerenderer:
    image: superlimitbreak/mediatimelinerenderer:latest
    volumes:
      - ${PATH_HOST_media}:/srv/media
    command: [
      '/srv/media',
      '--daemon_scan_interval_seconds', '60',
    ]

  stageorchestration:
    image: superlimitbreak/stageorchestration:latest
    ports:
      - "23487:23487"
    #expose:
    #  - 23487
    #volumes:
      #- ${ROOT_FOLDER}/stageOrchestration/data/sequences:/stageOrchestration/data/sequences/:ro
      #- ${PATH_HOST_media}/stageOrchestrationSequences:/stageOrchestration/data/sequences/:ro
      #- ${PATH_HOST_media}/stageDescription:/stageOrchestration/data/stageDescription/:ro
    links:
      #- mediainfoservice
      - subscriptionserver
    command: [
      '--config=config.development.yaml',
      '--subscriptionserver_uri=ws://subscriptionserver:9873',
      '--media_url=http://displaytrigger/media',
      '--mediainfo_url=http://displaytrigger/mediainfo',
      '--timeoffset_lights_seconds=${STAGEORCHESTRATION_timeoffset_lights_seconds}',
      '--timeoffset_media_seconds=${STAGEORCHESTRATION_timeoffset_media_seconds}',
    ]

    # TODO: Add udp->websocket bridge?
