version: '3.6'

services:

  displaytrigger:
    image: superlimitbreak/displaytrigger:latest
    ports:
      - "80:80"
    volumes:
      - ${PATH_HOST_media}:/srv/media/:ro
      - ${PATH_HOST_media}:/srv/eventmap/:ro  # Attempt to simplify the deployment. eventmap .json files are in the root of media
    links:
      - subscriptionserver

  # TODO: Add falcon_bridge

  subscriptionserver:
    image: superlimitbreak/subscriptionserver:latest
    ports:
      - "9872:9872"
      - "9873:9873"

  stageorchestration:
    image: superlimitbreak/stageorchestration:latest
    ports:
      - "23487:23487"
    links:
      - subscriptionserver
    command: --config config.development.yaml --displaytrigger_host subscriptionserver
